### ISSUE TITLE
proxy httpclient does not release connection pool when frontend close chunked response

### ISSUE THREAD

**Issue by hdfg159** [eclipse-vertx/vertx-http-proxy#91]
### Questions

When the server responds with a chunked response, sending one chunk and then not sending the next one for a long time, and the frontend actively closes the connection, it will cause the ProxyHttpClientConnection to be reclaimed only when the next data is sent.

### Version

v4.5.8

### Context

#90 

### Do you have a reproducer?

In the test class submitted with the pull request.

### Steps to reproduce

1. Run test io.vertx.tests.ProxyClientKeepAliveTest#testFrontendCloseChunkedResponse

### Extra

* Corretto 21.0.1
* Windows 10

**Comment by tsegismont** [comment]
Fixed by 477ca41

**Comment by tsegismont** [comment]
Reverted 477ca41 with 5ec808d because of #94

**Comment by tsegismont** [comment]
I've fixed the test in #98 and it passes without changes in the code.

So I'll go ahead and close this issue. Please reopen if you can provide a test that demonstrates the problem.

**Comment by hdfg159** [comment]
@tsegismont Hello~ This issue still exists. The reason it cannot be reproduced is that the test class is incorrect

**Comment by hdfg159** [comment]
PR: #115
Related issue: [https://github.com/eclipse-vertx/vert.x/issues/3524](https://github.com/eclipse-vertx/vert.x/issues/3524)
